spring:
  datasource:
    url: jdbc:postgresql://autorack.proxy.rlwy.net:19378/railway
    username: postgres
    password: kYqrilpPLRTdHpcJiKGWrKqaCtwDGLvt
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  key:
    access-token:
      private-key: D:\Workspace\java\bodyguard_us\certs\access_token\private_key.pem
      public-key: D:\Workspace\java\bodyguard_us\certs\access_token\public_key.pem
      expireIn: 2 # hours
    refresh-token:
      private-key: D:\Workspace\java\bodyguard_us\certs\refresh_token\private_key.pem
      public-key: D:\Workspace\java\bodyguard_us\certs\refresh_token\public_key.pem
      expireIn: 120 # hour == 5 days
admin:
  email: admin@gmail.com
  password: ABCabc123@
upload:
  path: D:/Workspace/java/bodyguards_us/upload