server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1/
  error:
    path: /error
    whitelabel:
      enabled: true

spring:
  profiles:
    active: dev
    default: dev
  application:
    name: bodyguards-us

springdoc:
  swagger-ui:
    path: "/docs"
    disable-swagger-default-url: true

jwt:
  key:
    access-token:
      private-key: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
      public-key: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
      expireIn: 2 # hour
    refresh-token:
      private-key: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
      public-key: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
      expireIn: 120 # hour == 5 days
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

upload:
  path: ${UPLOAD_PATH}