server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1/
  error:
    path: /error
    whitelabel:
      enabled: true

spring:
  profiles:
    active: dev
    default: dev
  application:
    name: bodyguards-us
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
