spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true
    username: sa
    password: password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  key:
    access-token:
      private-key: D:\Workspace\java\bodyguards_us\certs\access_token\private-key.pem
      public-key: D:\Workspace\java\bodyguards_us\certs\access_token\public-key.pem
      expireIn: 2 # hours
    refresh-token:
      private-key: D:\Workspace\java\bodyguards_us\certs\refresh_token\private-key.pem
      public-key: D:\Workspace\java\bodyguards_us\certs\refresh_token\public-key.pem
      expireIn: 120 # hour == 5 days