server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1/
  error:
    path: /error
    whitelabel:
      enabled: true

spring:
  profiles:
    active: pg
    default: dev
  application:
    name: bodyguards-us
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME}U
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: "/docs"
    disable-swagger-default-url: true

jwt:
  key:
    access-token:
      private-key: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
      public-key: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
      expireIn: 2 # hour
    refresh-token:
      private-key: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
      public-key: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
      expireIn: 120 # hour == 5 days
admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

upload:
  path: ${UPLOAD_PATH}