spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true;databaseName=bodyguard
    username: NTTH
    password: boiduongvan1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database: sql_server
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  key:
    access-token:
      private-key: D:\Inter_07_2024\access_token-20240812T082145Z-001\access_token\private_key.pem
      public-key: D:\Inter_07_2024\access_token-20240812T082145Z-001\access_token\public_key.pem
      expireIn: 2 # hours
    refresh-token:
      private-key: D:\Inter_07_2024\refresh_token-20240812T082129Z-001\refresh_token\private_key.pem
      public-key: D:\Inter_07_2024\refresh_token-20240812T082129Z-001\refresh_token\public_key.pem
      expireIn: 120 # hour == 5 days
admin:
  email: admin@gmail.com
  password: 12345678