spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:15256/railway
    username: postgres
    password: YTRqBsjTUBjmOlhFHifqdOkaldkqUTgn
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  key:
    access-token:
      private-key: D:\Inter_07_2024\access_token-20240812T082145Z-001\access_token\private_key.pem
      public-key: D:\Inter_07_2024\access_token-20240812T082145Z-001\access_token\public_key.pem
      expireIn: 2 # hours
    refresh-token:
      private-key: D:\Inter_07_2024\refresh_token-20240812T082129Z-001\refresh_token\private_key.pem
      public-key: D:\Inter_07_2024\refresh_token-20240812T082129Z-001\refresh_token\public_key.pem
      expireIn: 120 # hour == 5 days
admin:
  email: admin@gmail.com
  password: ABCabc123@